### ISSUE TITLE
Usage limits exceeded

### ISSUE THREAD

**Issue by dizdeveloper** [surreydigitalservices/locate-api#2]
API users are getting {"error":"Exceed usage limits"} message . Probably to do with the recent restore of Live server to a previous state ?

**Comment by pmackay** [comment]
Can you give some more info? On which user account (what name)?

**Comment by dizdeveloper** [comment]
We have one token we use for all API calls made by Surreycc . I will email you the token

**Comment by pmackay** [comment]
@dizdeveloper is this better now?

**Comment by dizdeveloper** [comment]
Yes , We didn't have this problem since increasing the limit to 30,000 a day . 
Thank you
